### ISSUE TITLE
Please include LoadForCreateWidgetsModule branch tag

### ISSUE THREAD

**Issue by RupenAnjaria** [ServiceNow/devtraining-needit-orlando#120]
Please include LoadForCreateWidgetsModule tag as it is required to complete widget training. 
This is mentioned here: https://developer.servicenow.com/dev.do#!/learn/courses/quebec/app_store_learnv2_serviceportal_quebec_service_portal/app_store_learnv2_serviceportal_quebec_creating_custom_widgets/app_store_learnv2_serviceportal_quebec_exercise_create_a_branch_for_creating_custom_widgets

**Comment by niedziel** [comment]
Thanks for dropping us a line.  The **LoadForCreateWidgetsModule** tag is not part of the _ServiceNow/devtraining-needit-orlando_ repository.  You need the _ServiceNow/devtraining-createnotes-orlando_ repo. The  [Exercise:  Fork Repository and Import Application for the Creating Custom Widgets Module](https://developer.servicenow.com/dev.do#!/learn/courses/quebec/app_store_learnv2_serviceportal_quebec_service_portal/app_store_learnv2_serviceportal_quebec_creating_custom_widgets/app_store_learnv2_serviceportal_quebec_exercise_create_a_branch_for_creating_custom_widgets) page contains the repo name.  

Best wishes for your widget creating endeavors!

**Comment by RupenAnjaria** [comment]
Thank you for the quick response. I was hoping to get it in here because most of my code is in Orlando repository.
