### ISSUE TITLE
Merge with NY version

### ISSUE THREAD

**Issue by JRV77** [ServiceNow/devtraining-needit-orlando#48]
Hi,
Sorry if this question is misplaced. I started my learning on NY version and without further thinking went on with upgrading to Orlando. Now, I have my NeedIt application linked to devtraining-needit-New-York repo.
Is their any changes in the Orlando repo that justifiy using the Orlando repo? If yes, what is the best way to proceed? Start all over again with Orlando or merge the two repo?
Thks.

**Comment by bsweets** [comment]
Hi,
We do have changes in the Orlando repo that might be confusing if you are still trying to use the New York repo. I do not remember all the changes off the top of my head, but an example is that some modules use a script to generate sample NeedIt records. In New York, you need to create the script record to run. In Orlando, the script is included in the repository, so you just need to run it and update it. 

Your best bet for new learning would be to:
1. save any work you have to your New York repository
2. delete the NeedIt application
3. disconnect the New York repository (see the [Troubleshooting GitHub Issues}(https://developer.servicenow.com/dev.do#!/guide/orlando/now-platform/github-guide/troubleshooting-github-issues) section of the _GitHub and the Developer Site Training Guide_)
4. fork and import the Orlando version of the repository

In the future, you can send feedback from any page on the Developer Site. If you are authenticated, we will easily be able to reply and get you feedback.

Happy developing,
Ben Sweetser
ServiceNow Developer Program
